name: speak
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - pytorch>=2.0.0
  - torchaudio>=2.0.0
  - librosa>=0.9.0
  - scikit-learn>=0.24.0
  - tqdm>=4.62.0
  - jupyter>=1.0.0
  - pip:
    - soundfile>=0.10.3
    - transformers>=4.15.0
    - datasets>=1.17.0
    - evaluate>=0.2.0
    - wandb>=0.12.0
    - hydra-core>=1.1.0
    - omegaconf>=2.1.0
    - tensorboard>=2.7.0 